import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

/*const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}*/

type Props = {
  children: ReactNode
}

export const metadata: Metadata = {
  // title: 'Site'
  title: {
    template: '%s - B7WEB', // Pega o title da pagina e completa
    default: 'B7WEB' // Caso nao tenha um title, coloca por padrao
  }
}

const Layout = ({ children }: Props) => {
  return(
    <html>
      <body>
        <h1>Layout</h1>
        <hr />
        
        <div>
          { children }
        </div>
      </body>

    </html>
  )
}

export default Layout
